<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE HolyQuran [
	<!ATTLIST HolyQuran TranslationID CDATA #REQUIRED>
	<!ATTLIST HolyQuran Writer CDATA #REQUIRED>
	<!ATTLIST HolyQuran Language CDATA #REQUIRED>
	<!ATTLIST HolyQuran LanguageIsoCode CDATA #REQUIRED>
	<!ATTLIST HolyQuran Direction (rtl|ltr) #REQUIRED>
	<!ELEMENT HolyQuran (Chapter+)>
	<!ATTLIST Chapter ChapterID CDATA #REQUIRED>
	<!ATTLIST Chapter ChapterName CDATA #REQUIRED>
	<!ELEMENT Chapter (Verse+)>
	<!ATTLIST Verse VerseID CDATA #REQUIRED>
	<!ELEMENT Verse (#PCDATA)>
]>
<!-- This SQL Query Generated at 18 January 2016 19:06 (UTC) from www.qurandatabase.org -->
<!--
Tanzil Quran Text
Copyright (C) 2008-2009 Tanzil.info
License: Creative Commons 3.0 Unported (by-nd)

This copy of quran text is carefully produced, highly
verified and continuously monitored by a group of specialists
at the Tanzil project.

TERMS OF USE:
- Permission is granted to copy and distribute verbatim copies
  of this text, but CHANGING IT IS NOT ALLOWED.

- This quran text can be used in any website or application,
  provided its source (Tanzil.info) is clearly indicated, and
  a link is made to http://tanzil.info to enable users to keep
  track of changes.

- This copyright notice shall be included in all verbatim copies
  of the text, and shall be reproduced appropriately in all files
  derived from or containing substantial portion of this text.

  Please check updates at: http://tanzil.info/updates/
-->
<HolyQuran TranslationID="1" Writer="(Original Book)" Language="Arabic" LanguageIsoCode="ara" Direction="rtl">
<Chapter ChapterID="1" ChapterName="&#1575$04$01@75@78@81@77;">
<Verse VerseID="1">&#1576$16@87$18$05$16; &#1575$04$04$17$14$07$16; &#1575$04@85$17$14@81$18$05$14$48$06$16; &#1575$04@85$17$14@81$16$10$05$16;</Verse>
<Verse VerseID="2">&#1575$04$18@81$14$05$18@83$15; &#1604$16$04$17$14$07$16; &#1585$14@76$17$16; &#1575$04$18@93$14@75$04$14$05$16$10$06$14;</Verse>
<Verse VerseID="3">&#1575$04@85$17$14@81$18$05$14$48$06$16; &#1575$04@85$17$14@81$16$10$05$16;</Verse>
<Verse VerseID="4">&#1605$14@75$04$16$03$16; &#1610$14$08$18$05$16; &#1575$04@83$17$16$10$06$16;</Verse>
<Verse VerseID="5">&#1573$16$10$17$14@75$03$14; &#1606$14@93$18@76$15@83$15; &#1608$14@73$16$10$17$14@75$03$14; &#1606$14@87$18@78$14@93$16$10$06$15;</Verse>
<Verse VerseID="6">&#1575$07$18@83$16$06$14@75; &#1575$04@89$17$16@85$14@75@91$14; &#1575$04$18$05$15@87$18@78$14$02$16$10$05$14;</Verse>
<Verse VerseID="7">&#1589$16@85$14@75@91$14; &#1575$04$17$14@84$16$10$06$14; &#1571$14$06$18@93$14$05$18@78$14; &#1593$14$04$14$10$18$07$16$05$18; &#1594$14$10$18@85$16; &#1575$04$18$05$14@94$18@90$15$08@76$16; &#1593$14$04$14$10$18$07$16$05$18; &#1608$14$04$14@75; &#1575$04@90$17$14@75$04$17$16$10$06$14;</Verse>
</Chapter>
<Chapter ChapterID="2" ChapterName="&#1575$04@76$02@85@77;">
<Verse VerseID="1">&#1576$16@87$18$05$16; &#1575$04$04$17$14$07$16; &#1575$04@85$17$14@81$18$05$14$48$06$16; &#1575$04@85$17$14@81$16$10$05$16; &#1575$04$05;</Verse>
<Verse VerseID="2">&#1584$14$48$04$16$03$14; &#1575$04$18$03$16@78$14@75@76$15; &#1604$14@75; &#1585$14$10$18@76$14; &#1755; &#1601$16$10$07$16; &#1755; &#1607$15@83$11$09; &#1604$16$04$18$05$15@78$17$14$02$16$10$06$14;</Verse>
<Verse VerseID="3">&#1575$04$17$14@84$16$10$06$14; &#1610$15@72$18$05$16$06$15$08$06$14; &#1576$16@75$04$18@94$14$10$18@76$16; &#1608$14$10$15$02$16$10$05$15$08$06$14; &#1575$04@89$17$14$04$14@75@77$14; &#1608$14$05$16$05$17$14@75; &#1585$14@86$14$02$18$06$14@75$07$15$05$18; &#1610$15$06$18$01$16$02$15$08$06$14;</Verse>
<Verse VerseID="4">&#1608$14@75$04$17$14@84$16$10$06$14; &#1610$15@72$18$05$16$06$15$08$06$14; &#1576$16$05$14@75; &#1571$15$06$18@86$16$04$14; &#1573$16$04$14$10$18$03$14; &#1608$14$05$14@75; &#1571$15$06$18@86$16$04$14; &#1605$16$06$18; &#1602$14@76$18$04$16$03$14; &#1608$14@76$16@75$04$18@70@82$16@85$14@77$16; &#1607$15$05$18; &#1610$15$08$02$16$06$15$08$06$14;</Verse>
<Verse VerseID="5">&#1571$15$08$04$14$48@74$16$03$14; &#1593$14$04$14$09$48; &#1607$15@83$11$09; &#1605$16$06$18; &#1585$14@76$17$16$07$16$05$18; &#1750; &#1608$14@71$15$08$04$14$48@74$16$03$14; &#1607$15$05$15; &#1575$04$18$05$15$01$18$04$16@81$15$08$06$14;</Verse>
<Verse VerseID="6">&#1573$16$06$17$14; &#1575$04$17$14@84$16$10$06$14; &#1603$14$01$14@85$15$08@75; &#1587$14$08$14@75@69$12; &#1593$14$04$14$10$18$07$16$05$18; &#1571$14@71$14$06$18@84$14@85$18@78$14$07$15$05$18; &#1571$14$05$18; &#1604$14$05$18; &#1578$15$06$18@84$16@85$18$07$15$05$18; &#1604$14@75; &#1610$15@72$18$05$16$06$15$08$06$14;</Verse>
<Verse VerseID="7">&#1582$14@78$14$05$14; &#1575$04$04$17$14$07$15; &#1593$14$04$14$09$48; &#1602$15$04$15$08@76$16$07$16$05$18; &#1608$14@93$14$04$14$09$48; &#1587$14$05$18@93$16$07$16$05$18; &#1750; &#1608$14@93$14$04$14$09$48; &#1571$14@76$18@89$14@75@85$16$07$16$05$18; &#1594$16@88$14@75$08$14@77$12; &#1750; &#1608$14$04$14$07$15$05$18; &#1593$14@84$14@75@76$12; &#1593$14@92$16$10$05$12;</Verse>
<Verse VerseID="8">&#1608$14$05$16$06$14; &#1575$04$06$17$14@75@87$16; &#1605$14$06$18; &#1610$14$02$15$08$04$15; &#1570$05$14$06$17$14@75; &#1576$16@75$04$04$17$14$07$16; &#1608$14@76$16@75$04$18$10$14$08$18$05$16; &#1575$04$18@70@82$16@85$16; &#1608$14$05$14@75; &#1607$15$05$18; &#1576$16$05$15@72$18$05$16$06$16$10$06$14;</Verse>
<Verse VerseID="9">&#1610$15@82$14@75@83$16@93$15$08$06$14; &#1575$04$04$17$14$07$14; &#1608$14@75$04$17$14@84$16$10$06$14; &#1570$05$14$06$15$08@75; &#1608$14$05$14@75; &#1610$14@82$18@83$14@93$15$08$06$14; &#1573$16$04$17$14@75; &#1571$14$06$18$01$15@87$14$07$15$05$18; &#1608$14$05$14@75; &#1610$14@88$18@93$15@85$15$08$06$14;</Verse>
<Verse VerseID="10">&#1601$16$10; &#1602$15$04$15$08@76$16$07$16$05$18; &#1605$14@85$14@90$12; &#1601$14@86$14@75@83$14$07$15$05$15; &#1575$04$04$17$14$07$15; &#1605$14@85$14@90$11@75; &#1750; &#1608$14$04$14$07$15$05$18; &#1593$14@84$14@75@76$12; &#1571$14$04$16$10$05$12; &#1576$16$05$14@75; &#1603$14@75$06$15$08@75; &#1610$14$03$18@84$16@76$15$08$06$14;</Verse>
<Verse VerseID="11">&#1608$14@73$16@84$14@75; &#1602$16$10$04$14; &#1604$14$07$15$05$18; &#1604$14@75; &#1578$15$01$18@87$16@83$15$08@75; &#1601$16$10; &#1575$04$18@71$14@85$18@90$16; &#1602$14@75$04$15$08@75; &#1573$16$06$17$14$05$14@75; &#1606$14@81$18$06$15; &#1605$15@89$18$04$16@81$15$08$06$14;</Verse>
<Verse VerseID="12">&#1571$14$04$14@75; &#1573$16$06$17$14$07$15$05$18; &#1607$15$05$15; &#1575$04$18$05$15$01$18@87$16@83$15$08$06$14; &#1608$14$04$14$48$03$16$06$18; &#1604$14@75; &#1610$14@88$18@93$15@85$15$08$06$14;</Verse>
<Verse VerseID="13">&#1608$14@73$16@84$14@75; &#1602$16$10$04$14; &#1604$14$07$15$05$18; &#1570$05$16$06$15$08@75; &#1603$14$05$14@75; &#1570$05$14$06$14; &#1575$04$06$17$14@75@87$15; &#1602$14@75$04$15$08@75; &#1571$14$06$15@72$18$05$16$06$15; &#1603$14$05$14@75; &#1570$05$14$06$14; &#1575$04@87$17$15$01$14$07$14@75@69$15; &#1751; &#1571$14$04$14@75; &#1573$16$06$17$14$07$15$05$18; &#1607$15$05$15; &#1575$04@87$17$15$01$14$07$14@75@69$15; &#1608$14$04$14$48$03$16$06$18; &#1604$14@75; &#1610$14@93$18$04$14$05$15$08$06$14;</Verse>
<Verse VerseID="14">&#1608$14@73$16@84$14@75; &#1604$14$02$15$08@75; &#1575$04$17$14@84$16$10$06$14; &#1570$05$14$06$15$08@75; &#1602$14@75$04$15$08@75; &#1570$05$14$06$17$14@75; &#1608$14@73$16@84$14@75; &#1582$14$04$14$08$18@75; &#1573$16$04$14$09$48; &#1588$14$10$14@75@91$16$10$06$16$07$16$05$18; &#1602$14@75$04$15$08@75; &#1573$16$06$17$14@75; &#1605$14@93$14$03$15$05$18; &#1573$16$06$17$14$05$14@75; &#1606$14@81$18$06$15; &#1605$15@87$18@78$14$07$18@86$16@74$15$08$06$14;</Verse>
<Verse VerseID="15">&#1575$04$04$17$14$07$15; &#1610$14@87$18@78$14$07$18@86$16@74$15; &#1576$16$07$16$05$18; &#1608$14$10$14$05$15@83$17$15$07$15$05$18; &#1601$16$10; &#1591$15@94$18$10$14@75$06$16$07$16$05$18; &#1610$14@93$18$05$14$07$15$08$06$14;</Verse>
<Verse VerseID="16">&#1571$15$08$04$14$48@74$16$03$14; &#1575$04$17$14@84$16$10$06$14; &#1575@88$18@78$14@85$14$08$15@75; &#1575$04@90$17$14$04$14@75$04$14@77$14; &#1576$16@75$04$18$07$15@83$14$09$48; &#1601$14$05$14@75; &#1585$14@76$16@81$14@78$18; &#1578$16@80$14@75@85$14@78$15$07$15$05$18; &#1608$14$05$14@75; &#1603$14@75$06$15$08@75; &#1605$15$07$18@78$14@83$16$10$06$14;</Verse>
<Verse VerseID="17">&#1605$14@79$14$04$15$07$15$05$18; &#1603$14$05$14@79$14$04$16; &#1575$04$17$14@84$16$10; &#1575@87$18@78$14$08$18$02$14@83$14; &#1606$14@75@85$11@75; &#1601$14$04$14$05$17$14@75; &#1571$14@90$14@75@69$14@78$18; &#1605$14@75; &#1581$14$08$18$04$14$07$15; &#1584$14$07$14@76$14; &#1575$04$04$17$14$07$15; &#1576$16$06$15$08@85$16$07$16$05$18; &#1608$14@78$14@85$14$03$14$07$15$05$18; &#1601$16$10; &#1592$15$04$15$05$14@75@78$13; &#1604$14@75; &#1610$15@76$18@89$16@85$15$08$06$14;</Verse>
<Verse VerseID="18">&#1589$15$05$17$12; &#1576$15$03$18$05$12; &#1593$15$05$18$10$12; &#1601$14$07$15$05$18; &#1604$14@75; &#1610$14@85$18@80$16@93$15$08$06$14;</Verse>
<Verse VerseID="19">&#1571$14$08$18; &#1603$14@89$14$10$17$16@76$13; &#1605$16$06$14; &#1575$04@87$17$14$05$14@75@69$16; &#1601$16$10$07$16; &#1592$15$04$15$05$14@75@78$12; &#1608$14@85$14@93$18@83$12; &#1608$14@76$14@85$18$02$12; &#1610$14@80$18@93$14$04$15$08$06$14; &#1571$14@89$14@75@76$16@93$14$07$15$05$18; &#1601$16$10; &#1570@84$14@75$06$16$07$16$05$18; &#1605$16$06$14; &#1575$04@89$17$14$08$14@75@93$16$02$16; &#1581$14@84$14@85$14; &#1575$04$18$05$14$08$18@78$16; &#1754; &#1608$14@75$04$04$17$14$07$15; &#1605$15@81$16$10@91$12; &#1576$16@75$04$18$03$14@75$01$16@85$16$10$06$14;</Verse>
<Verse VerseID="20">&#1610$14$03$14@75@83$15; &#1575$04$18@76$14@85$18$02$15; &#1610$14@82$18@91$14$01$15; &#1571$14@76$18@89$14@75@85$14$07$15$05$18; &#1750; &#1603$15$04$17$14$05$14@75; &#1571$14@90$14@75@69$14; &#1604$14$07$15$05$18; &#1605$14@88$14$08$18@75; &#1601$16$10$07$16; &#1608$14@73$16@84$14@75; &#1571$14@92$18$04$14$05$14; &#1593$14$04$14$10$18$07$16$05$18; &#1602$14@75$05$15$08@75; &#1754; &#1608$14$04$14$08$18; &#1588$14@75@69$14; &#1575$04$04$17$14$07$15; &#1604$14@84$14$07$14@76$14; &#1576$16@87$14$05$18@93$16$07$16$05$18; &#1608$14@71$14@76$18@89$14@75@85$16$07$16$05$18; &#1754; &#1573$16$06$17$14; &#1575$04$04$17$14$07$14; &#1593$14$04$14$09$48; &#1603$15$04$17$16; &#1588$14$10$18@69$13; &#1602$14@83$16$10@85$12;</Verse>
<Verse VerseID="21">&#1610$14@75; &#1571$14$10$17$15$07$14@75; &#1575$04$06$17$14@75@87$15; &#1575@93$18@76$15@83$15$08@75; &#1585$14@76$17$14$03$15$05$15; &#1575$04$17$14@84$16$10; &#1582$14$04$14$02$14$03$15$05$18; &#1608$14@75$04$17$14@84$16$10$06$14; &#1605$16$06$18; &#1602$14@76$18$04$16$03$15$05$18; &#1604$14@93$14$04$17$14$03$15$05$18; &#1578$14@78$17$14$02$15$08$06$14;</Verse>
<Verse VerseID="22">&#1575$04$17$14@84$16$10; &#1580$14@93$14$04$14; &#1604$14$03$15$05$15; &#1575$04$18@71$14@85$18@90$14; &#1601$16@85$14@75@88$11@75; &#1608$14@75$04@87$17$14$05$14@75@69$14; &#1576$16$06$14@75@69$11; &#1608$14@71$14$06$18@86$14$04$14; &#1605$16$06$14; &#1575$04@87$17$14$05$14@75@69$16; &#1605$14@75@69$11; &#1601$14@71$14@82$18@85$14@80$14; &#1576$16$07$16; &#1605$16$06$14; &#1575$04@79$17$14$05$14@85$14@75@78$16; &#1585$16@86$18$02$11@75; &#1604$14$03$15$05$18; &#1750; &#1601$14$04$14@75; &#1578$14@80$18@93$14$04$15$08@75; &#1604$16$04$17$14$07$16; &#1571$14$06$18@83$14@75@83$11@75; &#1608$14@71$14$06$18@78$15$05$18; &#1578$14@93$18$04$14$05$15$08$06$14;</Verse>
<Verse VerseID="23">&#1608$14@73$16$06$18; &#1603$15$06$18@78$15$05$18; &#1601$16$10; &#1585$14$10$18@76$13; &#1605$16$05$17$14@75; &#1606$14@86$17$14$04$18$06$14@75; &#1593$14$04$14$09$48; &#1593$14@76$18@83$16$06$14@75; &#1601$14@71$18@78$15$08@75; &#1576$16@87$15$08@85$14@77$13; &#1605$16$06$18; &#1605$16@79$18$04$16$07$16; &#1608$14@75@83$18@93$15$08@75; &#1588$15$07$14@83$14@75@69$14$03$15$05$18; &#1605$16$06$18; &#1583$15$08$06$16; &#1575$04$04$17$14$07$16; &#1573$16$06$18; &#1603$15$06$18@78$15$05$18; &#1589$14@75@83$16$02$16$10$06$14;</Verse>
<Verse VerseID="24">&#1601$14@73$16$06$18; &#1604$14$05$18; &#1578$14$01$18@93$14$04$15$08@75; &#1608$14$04$14$06$18; &#1578$14$01$18@93$14$04$15$08@75; &#1601$14@75@78$17$14$02$15$08@75; &#1575$04$06$17$14@75@85$14; &#1575$04$17$14@78$16$10; &#1608$14$02$15$08@83$15$07$14@75; &#1575$04$06$17$14@75@87$15; &#1608$14@75$04$18@81$16@80$14@75@85$14@77$15; &#1750; &#1571$15@93$16@83$17$14@78$18; &#1604$16$04$18$03$14@75$01$16@85$16$10$06$14;</Verse>
<Verse VerseID="25">&#1608$14@76$14@88$17$16@85$16; &#1575$04$17$14@84$16$10$06$14; &#1570$05$14$06$15$08@75; &#1608$14@93$14$05$16$04$15$08@75; &#1575$04@89$17$14@75$04$16@81$14@75@78$16; &#1571$14$06$17$14; &#1604$14$07$15$05$18; &#1580$14$06$17$14@75@78$13; &#1578$14@80$18@85$16$10; &#1605$16$06$18; &#1578$14@81$18@78$16$07$14@75; &#1575$04$18@71$14$06$18$07$14@75@85$15; &#1750; &#1603$15$04$17$14$05$14@75; &#1585$15@86$16$02$15$08@75; &#1605$16$06$18$07$14@75; &#1605$16$06$18; &#1579$14$05$14@85$14@77$13; &#1585$16@86$18$02$11@75; &#1753; &#1602$14@75$04$15$08@75; &#1607$14$48@84$14@75; &#1575$04$17$14@84$16$10; &#1585$15@86$16$02$18$06$14@75; &#1605$16$06$18; &#1602$14@76$18$04$15; &#1750; &#1608$14@71$15@78$15$08@75; &#1576$16$07$16; &#1605$15@78$14@88$14@75@76$16$07$11@75; &#1750; &#1608$14$04$14$07$15$05$18; &#1601$16$10$07$14@75; &#1571$14@86$18$08$14@75@80$12; &#1605$15@91$14$07$17$14@85$14@77$12; &#1750; &#1608$14$07$15$05$18; &#1601$16$10$07$14@75; &#1582$14@75$04$16@83$15$08$06$14;</Verse>
<Verse VerseID="26">&#1573$16$06$17$14; &#1575$04$04$17$14$07$14; &#1604$14@75; &#1610$14@87$18@78$14@81$18$10$16$10; &#1571$14$06$18; &#1610$14@90$18@85$16@76$14; &#1605$14@79$14$04$11@75; &#1605$14@75; &#1576$14@93$15$08@90$14@77$11; &#1601$14$05$14@75; &#1601$14$08$18$02$14$07$14@75; &#1754; &#1601$14@71$14$05$17$14@75; &#1575$04$17$14@84$16$10$06$14; &#1570$05$14$06$15$08@75; &#1601$14$10$14@93$18$04$14$05$15$08$06$14; &#1571$14$06$17$14$07$15; &#1575$04$18@81$14$02$17$15; &#1605$16$06$18; &#1585$14@76$17$16$07$16$05$18; &#1750; &#1608$14@71$14$05$17$14@75; &#1575$04$17$14@84$16$10$06$14; &#1603$14$01$14@85$15$08@75; &#1601$14$10$14$02$15$08$04$15$08$06$14; &#1605$14@75@84$14@75; &#1571$14@85$14@75@83$14; &#1575$04$04$17$14$07$15; &#1576$16$07$14$48@84$14@75; &#1605$14@79$14$04$11@75; &#1752; &#1610$15@90$16$04$17$15; &#1576$16$07$16; &#1603$14@79$16$10@85$11@75; &#1608$14$10$14$07$18@83$16$10; &#1576$16$07$16; &#1603$14@79$16$10@85$11@75; &#1754; &#1608$14$05$14@75; &#1610$15@90$16$04$17$15; &#1576$16$07$16; &#1573$16$04$17$14@75; &#1575$04$18$01$14@75@87$16$02$16$10$06$14;</Verse>
<Verse VerseID="27">&#1575$04$17$14@84$16$10$06$14; &#1610$14$06$18$02$15@90$15$08$06$14; &#1593$14$07$18@83$14; &#1575$04$04$17$14$07$16; &#1605$16$06$18; &#1576$14@93$18@83$16; &#1605$16$10@79$14@75$02$16$07$16; &#1608$14$10$14$02$18@91$14@93$15$08$06$14; &#1605$14@75; &#1571$14$05$14@85$14; &#1575$04$04$17$14$07$15; &#1576$16$07$16; &#1571$14$06$18; &#1610$15$08@89$14$04$14; &#1608$14$10$15$01$18@87$16@83$15$08$06$14; &#1601$16$10; &#1575$04$18@71$14@85$18@90$16; &#1754; &#1571$15$08$04$14$48@74$16$03$14; &#1607$15$05$15; &#1575$04$18@82$14@75@87$16@85$15$08$06$14;</Verse>
<Verse VerseID="28">&#1603$14$10$18$01$14; &#1578$14$03$18$01$15@85$15$08$06$14; &#1576$16@75$04$04$17$14$07$16; &#1608$14$03$15$06$18@78$15$05$18; &#1571$14$05$18$08$14@75@78$11@75; &#1601$14@71$14@81$18$10$14@75$03$15$05$18; &#1750; &#1579$15$05$17$14; &#1610$15$05$16$10@78$15$03$15$05$18; &#1579$15$05$17$14; &#1610$15@81$18$10$16$10$03$15$05$18; &#1579$15$05$17$14; &#1573$16$04$14$10$18$07$16; &#1578$15@85$18@80$14@93$15$08$06$14;</Verse>
<Verse VerseID="29">&#1607$15$08$14; &#1575$04$17$14@84$16$10; &#1582$14$04$14$02$14; &#1604$14$03$15$05$18; &#1605$14@75; &#1601$16$10; &#1575$04$18@71$14@85$18@90$16; &#1580$14$05$16$10@93$11@75; &#1579$15$05$17$14; &#1575@87$18@78$14$08$14$09$48; &#1573$16$04$14$09; &#1575$04@87$17$14$05$14@75@69$16; &#1601$14@87$14$08$17$14@75$07$15$06$17$14; &#1587$14@76$18@93$14; &#1587$14$05$14@75$08$14@75@78$13; &#1754; &#1608$14$07$15$08$14; &#1576$16$03$15$04$17$16; &#1588$14$10$18@69$13; &#1593$14$04$16$10$05$12;</Verse>
<Verse VerseID="30">&#1608$14@73$16@84$18; &#1602$14@75$04$14; &#1585$14@76$17$15$03$14; &#1604$16$04$18$05$14$04$14@75@74$16$03$14@77$16; &#1573$16$06$17$16$10; &#1580$14@75@93$16$04$12; &#1601$16$10; &#1575$04$18@71$14@85$18@90$16; &#1582$14$04$16$10$01$14@77$11; &#1750; &#1602$14@75$04$15$08@75; &#1571$14@78$14@80$18@93$14$04$15; &#1601$16$10$07$14@75; &#1605$14$06$18; &#1610$15$01$18@87$16@83$15; &#1601$16$10$07$14@75; &#1608$14$10$14@87$18$01$16$03$15; &#1575$04@83$17$16$05$14@75@69$14; &#1608$14$06$14@81$18$06$15; &#1606$15@87$14@76$17$16@81$15; &#1576$16@81$14$05$18@83$16$03$14; &#1608$14$06$15$02$14@83$17$16@87$15; &#1604$14$03$14; &#1750; &#1602$14@75$04$14; &#1573$16$06$17$16$10; &#1571$14@93$18$04$14$05$15; &#1605$14@75; &#1604$14@75; &#1578$14@93$18$04$14$05$15$08$06$14;</Verse>
<Verse VerseID="31">&#1608$14@93$14$04$17$14$05$14; &#1570@83$14$05$14; &#1575$04$18@71$14@87$18$05$14@75@69$14; &#1603$15$04$17$14$07$14@75; &#1579$15$05$17$14; &#1593$14@85$14@90$14$07$15$05$18; &#1593$14$04$14$09; &#1575$04$18$05$14$04$14@75@74$16$03$14@77$16; &#1601$14$02$14@75$04$14; &#1571$14$06$18@76$16@74$15$08$06$16$10; &#1576$16@71$14@87$18$05$14@75@69$16; &#1607$14$48@72$15$04$14@75@69$16; &#1573$16$06$18; &#1603$15$06$18@78$15$05$18; &#1589$14@75@83$16$02$16$10$06$14;</Verse>
<Verse VerseID="32">&#1602$14@75$04$15$08@75; &#1587$15@76$18@81$14@75$06$14$03$14; &#1604$14@75; &#1593$16$04$18$05$14; &#1604$14$06$14@75; &#1573$16$04$17$14@75; &#1605$14@75; &#1593$14$04$17$14$05$18@78$14$06$14@75; &#1750; &#1573$16$06$17$14$03$14; &#1571$14$06$18@78$14; &#1575$04$18@93$14$04$16$10$05$15; &#1575$04$18@81$14$03$16$10$05$15;</Verse>
<Verse VerseID="33">&#1602$14@75$04$14; &#1610$14@75; &#1570@83$14$05$15; &#1571$14$06$18@76$16@74$18$07$15$05$18; &#1576$16@71$14@87$18$05$14@75@74$16$07$16$05$18; &#1750; &#1601$14$04$14$05$17$14@75; &#1571$14$06$18@76$14@71$14$07$15$05$18; &#1576$16@71$14@87$18$05$14@75@74$16$07$16$05$18; &#1602$14@75$04$14; &#1571$14$04$14$05$18; &#1571$14$02$15$04$18; &#1604$14$03$15$05$18; &#1573$16$06$17$16$10; &#1571$14@93$18$04$14$05$15; &#1594$14$10$18@76$14; &#1575$04@87$17$14$05$14@75$08$14@75@78$16; &#1608$14@75$04$18@71$14@85$18@90$16; &#1608$14@71$14@93$18$04$14$05$15; &#1605$14@75; &#1578$15@76$18@83$15$08$06$14; &#1608$14$05$14@75; &#1603$15$06$18@78$15$05$18; &#1578$14$03$18@78$15$05$15$08$06$14;</Verse>
<Verse VerseID="34">&#1608$14@73$16@84$18; &#1602$15$04$18$06$14@75; &#1604$16$04$18$05$14$04$14@75@74$16$03$14@77$16; &#1575@87$18@80$15@83$15$08@75; &#1604$16@70@83$14$05$14; &#1601$14@87$14@80$14@83$15$08@75; &#1573$16$04$17$14@75; &#1573$16@76$18$04$16$10@87$14; &#1571$14@76$14$09$48; &#1608$14@75@87$18@78$14$03$18@76$14@85$14; &#1608$14$03$14@75$06$14; &#1605$16$06$14; &#1575$04$18$03$14@75$01$16@85$16$10$06$14;</Verse>
<Verse VerseID="35">&#1608$14$02$15$04$18$06$14@75; &#1610$14@75; &#1570@83$14$05$15; &#1575@87$18$03$15$06$18; &#1571$14$06$18@78$14; &#1608$14@86$14$08$18@80$15$03$14; &#1575$04$18@80$14$06$17$14@77$14; &#1608$14$03$15$04$14@75; &#1605$16$06$18$07$14@75; &#1585$14@94$14@83$11@75; &#1581$14$10$18@79$15; &#1588$16@74$18@78$15$05$14@75; &#1608$14$04$14@75; &#1578$14$02$18@85$14@76$14@75; &#1607$14$48@84$16$07$16; &#1575$04@88$17$14@80$14@85$14@77$14; &#1601$14@78$14$03$15$08$06$14@75; &#1605$16$06$14; &#1575$04@92$17$14@75$04$16$05$16$10$06$14;</Verse>
<Verse VerseID="36">&#1601$14@71$14@86$14$04$17$14$07$15$05$14@75; &#1575$04@88$17$14$10$18@91$14@75$06$15; &#1593$14$06$18$07$14@75; &#1601$14@71$14@82$18@85$14@80$14$07$15$05$14@75; &#1605$16$05$17$14@75; &#1603$14@75$06$14@75; &#1601$16$10$07$16; &#1750; &#1608$14$02$15$04$18$06$14@75; &#1575$07$18@76$16@91$15$08@75; &#1576$14@93$18@90$15$03$15$05$18; &#1604$16@76$14@93$18@90$13; &#1593$14@83$15$08$17$12; &#1750; &#1608$14$04$14$03$15$05$18; &#1601$16$10; &#1575$04$18@71$14@85$18@90$16; &#1605$15@87$18@78$14$02$14@85$17$12; &#1608$14$05$14@78$14@75@93$12; &#1573$16$04$14$09$48; &#1581$16$10$06$13;</Verse>
<Verse VerseID="37">&#1601$14@78$14$04$14$02$17$14$09$48; &#1570@83$14$05$15; &#1605$16$06$18; &#1585$14@76$17$16$07$16; &#1603$14$04$16$05$14@75@78$13; &#1601$14@78$14@75@76$14; &#1593$14$04$14$10$18$07$16; &#1754; &#1573$16$06$17$14$07$15; &#1607$15$08$14; &#1575$04@78$17$14$08$17$14@75@76$15; &#1575$04@85$17$14@81$16$10$05$15;</Verse>
<Verse VerseID="38">&#1602$15$04$18$06$14@75; &#1575$07$18@76$16@91$15$08@75; &#1605$16$06$18$07$14@75; &#1580$14$05$16$10@93$11@75; &#1750; &#1601$14@73$16$05$17$14@75; &#1610$14@71$18@78$16$10$14$06$17$14$03$15$05$18; &#1605$16$06$17$16$10; &#1607$15@83$11$09; &#1601$14$05$14$06$18; &#1578$14@76$16@93$14; &#1607$15@83$14@75$10$14; &#1601$14$04$14@75; &#1582$14$08$18$01$12; &#1593$14$04$14$10$18$07$16$05$18; &#1608$14$04$14@75; &#1607$15$05$18; &#1610$14@81$18@86$14$06$15$08$06$14;</Verse>
<Verse VerseID="39">&#1608$14@75$04$17$14@84$16$10$06$14; &#1603$14$01$14@85$15$08@75; &#1608$14$03$14@84$17$14@76$15$08@75; &#1576$16@70$10$14@75@78$16$06$14@75; &#1571$15$08$04$14$48@74$16$03$14; &#1571$14@89$18@81$14@75@76$15; &#1575$04$06$17$14@75@85$16; &#1750; &#1607$15$05$18; &#1601$16$10$07$14@75; &#1582$14@75$04$16@83$15$08$06$14;</Verse>
<Verse VerseID="40">&#1610$14@75; &#1576$14$06$16$10; &#1573$16@87$18@85$14@75@74$16$10$04$14; &#1575@84$18$03$15@85$15$08@75; &#1606$16@93$18$05$14@78$16$10$14; &#1575$04$17$14@78$16$10; &#1571$14$06$18@93$14$05$18@78$15; &#1593$14$04$14$10$18$03$15$05$18; &#1608$14@71$14$08$18$01$15$08@75; &#1576$16@93$14$07$18@83$16$10; &#1571$15$08$01$16; &#1576$16@93$14$07$18@83$16$03$15$05$18; &#1608$14@73$16$10$17$14@75$10$14; &#1601$14@75@85$18$07$14@76$15$08$06$16;</Verse>
<Verse VerseID="41">&#1608$14@70$05$16$06$15$08@75; &#1576$16$05$14@75; &#1571$14$06$18@86$14$04$18@78$15; &#1605$15@89$14@83$17$16$02$11@75; &#1604$16$05$14@75; &#1605$14@93$14$03$15$05$18; &#1608$14$04$14@75; &#1578$14$03$15$08$06$15$08@75; &#1571$14$08$17$14$04$14; &#1603$14@75$01$16@85$13; &#1576$16$07$16; &#1750; &#1608$14$04$14@75; &#1578$14@88$18@78$14@85$15$08@75; &#1576$16@70$10$14@75@78$16$10; &#1579$14$05$14$06$11@75; &#1602$14$04$16$10$04$11@75; &#1608$14@73$16$10$17$14@75$10$14; &#1601$14@75@78$17$14$02$15$08$06$16;</Verse>
<Verse VerseID="42">&#1608$14$04$14@75; &#1578$14$04$18@76$16@87$15$08@75; &#1575$04$18@81$14$02$17$14; &#1576$16@75$04$18@76$14@75@91$16$04$16; &#1608$14@78$14$03$18@78$15$05$15$08@75; &#1575$04$18@81$14$02$17$14; &#1608$14@71$14$06$18@78$15$05$18; &#1578$14@93$18$04$14$05$15$08$06$14;</Verse>
<Verse VerseID="43">&#1608$14@71$14$02$16$10$05$15$08@75; &#1575$04@89$17$14$04$14@75@77$14; &#1608$14@70@78$15$08@75; &#1575$04@86$17$14$03$14@75@77$14; &#1608$14@75@85$18$03$14@93$15$08@75; &#1605$14@93$14; &#1575$04@85$17$14@75$03$16@93$16$10$06$14;</Verse>
<Verse VerseID="44">&#1571$14@78$14@71$18$05$15@85$15$08$06$14; &#1575$04$06$17$14@75@87$14; &#1576$16@75$04$18@76$16@85$17$16; &#1608$14@78$14$06$18@87$14$08$18$06$14; &#1571$14$06$18$01$15@87$14$03$15$05$18; &#1608$14@71$14$06$18@78$15$05$18; &#1578$14@78$18$04$15$08$06$14; &#1575$04$18$03$16@78$14@75@76$14; &#1754; &#1571$14$01$14$04$14@75; &#1578$14@93$18$02$16$04$15$08$06$14;</Verse>
<Verse VerseID="45">&#1608$14@75@87$18@78$14@93$16$10$06$15$08@75; &#1576$16@75$04@89$17$14@76$18@85$16; &#1608$14@75$04@89$17$14$04$14@75@77$16; &#1754; &#1608$14@73$16$06$17$14$07$14@75; &#1604$14$03$14@76$16$10@85$14@77$12; &#1573$16$04$17$14@75; &#1593$14$04$14$09; &#1575$04$18@82$14@75@88$16@93$16$10$06$14;</Verse>
<Verse VerseID="46">&#1575$04$17$14@84$16$10$06$14; &#1610$14@92$15$06$17$15$08$06$14; &#1571$14$06$17$14$07$15$05$18; &#1605$15$04$14@75$02$15$08; &#1585$14@76$17$16$07$16$05$18; &#1608$14@71$14$06$17$14$07$15$05$18; &#1573$16$04$14$10$18$07$16; &#1585$14@75@80$16@93$15$08$06$14;</Verse>
<Verse VerseID="47">&#1610$14@75; &#1576$14$06$16$10; &#1573$16@87$18@85$14@75@74$16$10$04$14; &#1575@84$18$03$15@85$15$08@75; &#1606$16@93$18$05$14@78$16$10$14; &#1575$04$17$14@78$16$10; &#1571$14$06$18@93$14$05$18@78$15; &#1593$14$04$14$10$18$03$15$05$18; &#1608$14@71$14$06$17$16$10; &#1601$14@90$17$14$04$18@78$15$03$15$05$18; &#1593$14$04$14$09; &#1575$04$18@93$14@75$04$14$05$16$10$06$14;</Verse>
<Verse VerseID="48">&#1608$14@75@78$17$14$02$15$08@75; &#1610$14$08$18$05$11@75; &#1604$14@75; &#1578$14@80$18@86$16$10; &#1606$14$01$18@87$12; &#1593$14$06$18; &#1606$14$01$18@87$13; &#1588$14$10$18@74$11@75; &#1608$14$04$14@75; &#1610$15$02$18@76$14$04$15; &#1605$16$06$18$07$14@75; &#1588$14$01$14@75@93$14@77$12; &#1608$14$04$14@75; &#1610$15@72$18@82$14@84$15; &#1605$16$06$18$07$14@75; &#1593$14@83$18$04$12; &#1608$14$04$14@75; &#1607$15$05$18; &#1610$15$06$18@89$14@85$15$08$06$14;</Verse>
<Verse VerseID="49">&#1608$14@73$16@84$18; &#1606$14@80$17$14$10$18$06$14@75$03$15$05$18; &#1605$16$06$18; &#1570$04$16; &#1601$16@85$18@93$14$08$18$06$14; &#1610$14@87$15$08$05$15$08$06$14$03$15$05$18; &#1587$15$08@69$14; &#1575$04$18@93$14@84$14@75@76$16; &#1610$15@84$14@76$17$16@81$15$08$06$14; &#1571$14@76$18$06$14@75@69$14$03$15$05$18; &#1608$14$10$14@87$18@78$14@81$18$10$15$08$06$14; &#1606$16@87$14@75@69$14$03$15$05$18; &#1754; &#1608$14$01$16$10; &#1584$14$48$04$16$03$15$05$18; &#1576$14$04$14@75@69$12; &#1605$16$06$18; &#1585$14@76$17$16$03$15$05$18; &#1593$14@92$16$10$05$12;</Verse>
<Verse VerseID="50">&#1608$14@73$16@84$18; &#1601$14@85$14$02$18$06$14@75; &#1576$16$03$15$05$15; &#1575$04$18@76$14@81$18@85$14; &#1601$14@71$14$06$18@80$14$10$18$06$14@75$03$15$05$18; &#1608$14@71$14@94$18@85$14$02$18$06$14@75; &#1570$04$14; &#1601$16@85$18@93$14$08$18$06$14; &#1608$14@71$14$06$18@78$15$05$18; &#1578$14$06$18@92$15@85$15$08$06$14;</Verse>
<Verse VerseID="51">&#1608$14@73$16@84$18; &#1608$14@75@93$14@83$18$06$14@75; &#1605$15$08@87$14$09$48; &#1571$14@85$18@76$14@93$16$10$06$14; &#1604$14$10$18$04$14@77$11; &#1579$15$05$17$14; &#1575@78$17$14@82$14@84$18@78$15$05$15; &#1575$04$18@93$16@80$18$04$14; &#1605$16$06$18; &#1576$14@93$18@83$16$07$16; &#1608$14@71$14$06$18@78$15$05$18; &#1592$14@75$04$16$05$15$08$06$14;</Verse>
<Verse VerseID="52">&#1579$15$05$17$14; &#1593$14$01$14$08$18$06$14@75; &#1593$14$06$18$03$15$05$18; &#1605$16$06$18; &#1576$14@93$18@83$16; &#1584$14$48$04$16$03$14; &#1604$14@93$14$04$17$14$03$15$05$18; &#1578$14@88$18$03$15@85$15$08$06$14;</Verse>
<Verse VerseID="53">&#1608$14@73$16@84$18; &#1570@78$14$10$18$06$14@75; &#1605$15$08@87$14$09; &#1575$04$18$03$16@78$14@75@76$14; &#1608$14@75$04$18$01$15@85$18$02$14@75$06$14; &#1604$14@93$14$04$17$14$03$15$05$18; &#1578$14$07$18@78$14@83$15$08$06$14;</Verse>
<Verse VerseID="54">&#1608$14@73$16@84$18; &#1602$14@75$04$14; &#1605$15$08@87$14$09$48; &#1604$16$02$14$08$18$05$16$07$16; &#1610$14@75; &#1602$14$08$18$05$16; &#1573$16$06$17$14$03$15$05$18; &#1592$14$04$14$05$18@78$15$05$18; &#1571$14$06$18$01$15@87$14$03$15$05$18; &#1576$16@75@78$17$16@82$14@75@84$16$03$15$05$15; &#1575$04$18@93$16@80$18$04$14; &#1601$14@78$15$08@76$15$08@75; &#1573$16$04$14$09$48; &#1576$14@75@85$16@74$16$03$15$05$18; &#1601$14@75$02$18@78$15$04$15$08@75; &#1571$14$06$18$01$15@87$14$03$15$05$18; &#1584$14$48$04$16$03$15$05$18; &#1582$14$10$18@85$12; &#1604$14$03$15$05$18; &#1593$16$06$18@83$14; &#1576$14@75@85$16@74$16$03$15$05$18; &#1601$14@78$14@75@76$14; &#1593$14$04$14$10$18$03$15$05$18; &#1754; &#1573$16$06$17$14$07$15; &#1607$15$08$14; &#1575$04@78$17$14$08$17$14@75@76$15; &#1575$04@85$17$14@81$16$10$05$15;</Verse>
<Verse VerseID="55">&#1608$14@73$16@84$18; &#1602$15$04$18@78$15$05$18; &#1610$14@75; &#1605$15$08@87$14$09$48; &#1604$14$06$18; &#1606$15@72$18$05$16$06$14; &#1604$14$03$14; &#1581$14@78$17$14$09$48; &#1606$14@85$14$09; &#1575$04$04$17$14$07$14; &#1580$14$07$18@85$14@77$11; &#1601$14@71$14@82$14@84$14@78$18$03$15$05$15; &#1575$04@89$17$14@75@93$16$02$14@77$15; &#1608$14@71$14$06$18@78$15$05$18; &#1578$14$06$18@92$15@85$15$08$06$14;</Verse>
<Verse VerseID="56">&#1579$15$05$17$14; &#1576$14@93$14@79$18$06$14@75$03$15$05$18; &#1605$16$06$18; &#1576$14@93$18@83$16; &#1605$14$08$18@78$16$03$15$05$18; &#1604$14@93$14$04$17$14$03$15$05$18; &#1578$14@88$18$03$15@85$15$08$06$14;</Verse>
<Verse VerseID="57">&#1608$14@92$14$04$17$14$04$18$06$14@75; &#1593$14$04$14$10$18$03$15$05$15; &#1575$04$18@94$14$05$14@75$05$14; &#1608$14@71$14$06$18@86$14$04$18$06$14@75; &#1593$14$04$14$10$18$03$15$05$15; &#1575$04$18$05$14$06$17$14; &#1608$14@75$04@87$17$14$04$18$08$14$09$48; &#1750; &#1603$15$04$15$08@75; &#1605$16$06$18; &#1591$14$10$17$16@76$14@75@78$16; &#1605$14@75; &#1585$14@86$14$02$18$06$14@75$03$15$05$18; &#1750; &#1608$14$05$14@75; &#1592$14$04$14$05$15$08$06$14@75; &#1608$14$04$14$48$03$16$06$18; &#1603$14@75$06$15$08@75; &#1571$14$06$18$01$15@87$14$07$15$05$18; &#1610$14@92$18$04$16$05$15$08$06$14;</Verse>
<Verse VerseID="58">&#1608$14@73$16@84$18; &#1602$15$04$18$06$14@75; &#1575@83$18@82$15$04$15$08@75; &#1607$14$48@84$16$07$16; &#1575$04$18$02$14@85$18$10$14@77$14; &#1601$14$03$15$04$15$08@75; &#1605$16$06$18$07$14@75; &#1581$14$10$18@79$15; &#1588$16@74$18@78$15$05$18; &#1585$14@94$14@83$11@75; &#1608$14@75@83$18@82$15$04$15$08@75; &#1575$04$18@76$14@75@76$14; &#1587$15@80$17$14@83$11@75; &#1608$14$02$15$08$04$15$08@75; &#1581$16@91$17$14@77$12; &#1606$14@94$18$01$16@85$18; &#1604$14$03$15$05$18; &#1582$14@91$14@75$10$14@75$03$15$05$18; &#1754; &#1608$14@87$14$06$14@86$16$10@83$15; &#1575$04$18$05$15@81$18@87$16$06$16$10$06$14;</Verse>
<Verse VerseID="59">&#1601$14@76$14@83$17$14$04$14; &#1575$04$17$14@84$16$10$06$14; &#1592$14$04$14$05$15$08@75; &#1602$14$08$18$04$11@75; &#1594$14$10$18@85$14; &#1575$04$17$14@84$16$10; &#1602$16$10$04$14; &#1604$14$07$15$05$18; &#1601$14@71$14$06$18@86$14$04$18$06$14@75; &#1593$14$04$14$09; &#1575$04$17$14@84$16$10$06$14; &#1592$14$04$14$05$15$08@75; &#1585$16@80$18@86$11@75; &#1605$16$06$14; &#1575$04@87$17$14$05$14@75@69$16; &#1576$16$05$14@75; &#1603$14@75$06$15$08@75; &#1610$14$01$18@87$15$02$15$08$06$14;</Verse>